### ISSUE TITLE
getting error while using widget-tweaks

### ISSUE THREAD

**Issue by azizulasif** [simhnna/django-widgets-improved#3]
While using django-widgets-improved and adding the widget-tweaks in INSTALLED_APPS, gives the following error:
django.core.exception.AppRegistryNotReady: Apps aren't loaded yet

**Comment by simhnna** [comment]
I have no idea where this is coming from, but I highly doubt it's an issue with this library

**Comment by azizulasif** [comment]
May be, works fine in linux but problem when loading Module in windows.

**Comment by simhnna** [comment]
Can you share a settings.py file or is the repo public?
Searching the internet for the error suggests that the issue is with the settings.py
